refs #955: deprecate Client::AUTH_* constants and replace them with AuthMethod::AUTH_* const
KnpLabs/php-github-api pull request #1036
Opened 2021-10-30 15:13 UTC by ipalo

Contribution for #955

2021-10-31 09:31 UTC, acrobat requested changes
Hi @ipalo, thanks for the PR! I've left a few comments on things that should be updated!

2021-10-31 09:31 UTC, acrobat commented on lib/Github/AuthMethod.php
> +    const AUTH_CLIENT_ID = 'client_id_header';
I woud remove the `AUTH_` prefix for these constants as the classname gives that context already (same for the other constants)

2021-10-31 09:31 UTC, acrobat commented on lib/Github/Client.php
> +     * @deprecated Use the AuthMethod const
```suggestion
     * @deprecated Use the Github\AuthMethod::CLIENT_ID const
```

Directly suggest the corresponding constant to make it easier for users who need to change their code

2021-10-31 09:31 UTC, acrobat commented on UPGRADE-3.0.md
> +* `Github\Client::AUTH_ACCESS_TOKEN`  use `Github\AuthMethod::AUTH_ACCESS_TOKEN` instead.
Please revert these changed as this is the upgrade file for v2 -> v3. Add your upgrade notes to the `UPGRADE-4.0.md` file.

2021-10-31 17:14 UTC, acrobat requested changes
One last minor change, otherwise the PR is good to go!

2021-10-31 17:14 UTC, acrobat commented on lib/Github/AuthMethod.php
> +    const CLIENT_ID = 'client_id_header';
Add the `public` const visibility to the constants in this class.

```suggestion
    public const CLIENT_ID = 'client_id_header';
```

2021-11-01 17:41 UTC, acrobat approved these changes

2021-11-02 06:51 UTC, merged

2021-11-02 06:52 UTC, acrobat commented
Thanks @ipalo! And congrats on your first contribution! 🎉

2021-11-08 16:17 UTC, ipalo commented
> Thanks @ipalo! And congrats on your first contribution! 🎉

Hi @acrobat! I noticed the PR hasn't yet been accepted for the Hacktoberfest. Could you unblock it with the "accepted" label? Thanks 🙌

2021-11-09 10:26 UTC, acrobat commented
@ipalo this should be ok already as the repository has the "hacktoberfest" topic. But I've added the accepted label to be sure.