Added environment variables & secrets
KnpLabs/php-github-api pull request #1104
Opened 2023-03-09 11:34 UTC by Froxz

Added environment:

[Secrets](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-environment-secrets)
[Variables](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#list-environment-variables)

2023-03-09 11:41 UTC, Froxz commented
Hi @acrobat when have time please review 👍

2023-03-09 20:51 UTC, acrobat requested changes

2023-03-09 20:51 UTC, acrobat commented on lib/Github/Api/Environment/Secrets.php
> +        }
I would not add this validation in our code, but let the github api validate the request and return any errors related to missing parameters. This way we won't block user in the future if github changes the required parameters

2023-03-09 20:51 UTC, acrobat commented on lib/Github/Api/Environment/Variables.php
> +        }
I would not add this validation in our code, but let the github api validate the request and return any errors related to missing parameters. This way we won't block user in the future if github changes the required parameters

2023-03-10 11:16 UTC, acrobat approved these changes

2023-03-10 11:17 UTC, merged

2023-03-10 11:17 UTC, acrobat commented
Thank you @Froxz

2023-03-10 11:17 UTC, Froxz commented
@acrobat Thank you.