Added Org & Repository varaibles
KnpLabs/php-github-api pull request #1106
Opened 2023-03-09 13:09 UTC by Froxz

2023-03-09 20:56 UTC, acrobat requested changes

2023-03-09 20:56 UTC, acrobat commented on lib/Github/Api/Organization/Actions/Variables.php
> +        }
I would not add this validation in our code, but let the github api validate the request and return any errors related to missing parameters. This way we won't block user in the future if github changes the required parameters

2023-03-09 20:56 UTC, acrobat commented on lib/Github/Api/Repository/Actions/Variables.php
> +        }
I would not add this validation in our code, but let the github api validate the request and return any errors related to missing parameters. This way we won't block user in the future if github changes the required parameters

2023-03-10 11:17 UTC, acrobat approved these changes

2023-03-10 11:18 UTC, merged

2023-03-10 11:18 UTC, acrobat commented
Thank you @Froxz

2023-03-10 11:18 UTC, Froxz commented
@acrobat thank you