Fix type error in ResultPager::fetch
KnpLabs/php-github-api pull request #1132
Opened 2024-03-03 15:05 UTC by nunoplopes

When using etags, the reply from github may be empty and the underlying APIs will return an empty string. We need to flip those to empty arrays.
e.g.:
```php
$github_builder
  ->addPlugin(new Http\Client\Common\Plugin\HeaderSetPlugin([
    'If-None-Match' => $etag,
  ]));

$api       = $github_client->user('user');
$paginator = new \Github\ResultPager($github_client);
$data      = $paginator->fetch($api, 'events', [$username]);
// $data should be [] if $etag is the latest
```

2024-03-24 14:15 UTC, acrobat requested changes
@nunoplopes thanks for the PR! Can you also add a test for this to avoid any regressions in the future? Thanks!

See: https://github.com/KnpLabs/php-github-api/blob/master/test/Github/Tests/ResultPagerTest.php

2024-03-25 09:28 UTC, nunoplopes commented
added tests + redone the fix based on the fix committed for #1135

2024-09-23 18:55 UTC, acrobat approved these changes

2024-09-23 18:55 UTC, merged

2024-09-23 18:55 UTC, acrobat commented
Thank you @nunoplopes