[WIP] Actions (#872)
KnpLabs/php-github-api pull request #939
Opened 2020-11-25 12:06 UTC by lexor

- [x] Artifacts
- [ ] Secrets
- [ ] Self-hosted runners
- [x] Workflows
- [x] Workflow jobs
- [x] Workflow runs

Documentation: https://developer.github.com/v3/actions/

2020-11-26 19:36 UTC, acrobat commented
Thanks for working on this @lexor! Let me know when it's ready for review 🚢

2020-11-27 16:08 UTC, fodinabor commented
What's missing from the developer.github.com documentation is e.g. dispatching:
https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event

2020-11-28 05:14 UTC, lexor commented
> What's missing from the developer.github.com documentation is e.g. dispatching:
> [docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event)

Thanks for `dispatches` function but this pull request based on [this documentation](https://developer.github.com/v3/actions/). After this pull request I can work on [this documentation](docs.github.com/en/free-pro-team@latest/rest/reference/actions).

I did not add organization endpoints because marked on documentation. Organization endpoints currently on public beta and can be change.

> Another note: `workflowId` is in most cases allowed to contain the filename of the workflow, so string should be preferred over int

Can you share example cases? I can't find example on docs.

2020-11-28 10:20 UTC, lexor commented
Hey @acrobat. This pull request awaiting review.

2020-11-28 10:32 UTC, fodinabor commented
For [Get a workflow](https://developer.github.com/v3/actions/workflows/#get-a-workflow) for example the docs write:

> Gets a specific workflow. You can also replace :workflow_id with :workflow_file_name. For example, you could use main.yml.

So, yeah I guess a string parameter named just workflow would make sense here.

2020-11-29 09:59 UTC, acrobat commented
@fodinabor the repo dispatch api endpoint is already added in #931

@lexor A general remark before I do a full review, can you update the doc links to directly link to the new documentation? Example: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions

2020-11-29 16:44 UTC, lexor commented
> @lexor A general remark before I do a full review, can you update the doc links to directly link to the new documentation? Example: [docs.github.com/en/free-pro-team@latest/rest/reference/actions](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions)

Done, I updated.

2020-11-29 19:03 UTC, acrobat requested changes
This comment is also applicable to all occurences of non-query parameters

> Can you replace the non url parameters with a `array $params/parameters `, so our code isn't fixed on a certain set of parameters of github decides to add new options.

Can you also add a docs entry for the added endpoints? The rest of PR looks good 👌

2020-11-29 20:35 UTC, lexor commented on lib/Github/Api/Repository/Actions/Artifacts.php
> +        // TODO(): Get `Location` header for download link.
Actually GitHub's download endpoints didn't return any json. Just needed take `Location` header value for download link. I tried already `$this->client->getLastResponse()->getHeader('Location')` but response didn't have `Location` header.

2020-11-30 07:22 UTC, acrobat commented on lib/Github/Api/Repository/Actions/Artifacts.php
> +        // TODO(): Get `Location` header for download link.
Can you do this call with curl and see if the header is present? If not it's a github issue

2020-11-30 07:34 UTC, lexor commented on lib/Github/Api/Repository/Actions/Artifacts.php
> +        // TODO(): Get `Location` header for download link.
If I use "curl" I can see the "location" header.

> λ ~/ curl -i -u lexor:$token https://api.github.com/repos/$username/$repo/actions/runs/$runId/logs
> HTTP/1.1 302 Found
> Status: 302 Found
> Location: https://pipelines.actions.githubusercontent.com/...

2020-11-30 07:43 UTC, acrobat commented on lib/Github/Api/Repository/Actions/Artifacts.php
> +        // TODO(): Get `Location` header for download link.
Can you check in your "test" setup if the 302 redirect is just followed by the client? I think guzzle will by default follow those redirect to the location specified and by that the request/response with the Location header is not returned for the last response.

2020-11-30 08:14 UTC, lexor commented on lib/Github/Api/Repository/Actions/Artifacts.php
> +        // TODO(): Get `Location` header for download link.
Yes, you are right. Guzzle is automatically redirects, `file_put_contents` solved issue.

2020-11-30 13:55 UTC, lexor commented
> Can you replace the non url parameters with a `array $params/parameters `, so our code isn't fixed on a certain set of parameters of github decides to add new options.

Sure, replaced. Now non url parameters moved on `array $parameters`.

> Can you also add a docs entry for the added endpoints? The rest of PR looks good 👌

I updated functions and test cases. Also added docs for added endpoints.

2020-12-03 11:28 UTC, acrobat approved these changes

2020-12-03 11:29 UTC, merged

2020-12-03 11:29 UTC, acrobat commented
Thanks @lexor! And congrats on your first contribution! 🎉

2021-04-14 14:10 UTC, dereuromark commented
What I am missing is the enable of a specific workflow
See https://docs.github.com/en/rest/reference/actions#enable-a-workflow

2021-04-14 14:16 UTC, lexor commented
> What I am missing is the enable of a specific workflow
> See [docs.github.com/en/rest/reference/actions#enable-a-workflow](https://docs.github.com/en/rest/reference/actions#enable-a-workflow)

Endpoint was just added or I missed it. I can create pull request for enable/disable endpoints.

2021-04-14 14:33 UTC, dereuromark commented
Yeah, might be new.
But I also struggle finding the right syntax.
The docs say this should work:
```php
$url = 'repos/' . rawurlencode($organization) . '/' . rawurlencode($repository) . '/actions/workflows/' . (string)$id . '/enable';

$this->post($url);
```

But it returns Not Found
I made sure to use a token that has permissions for "Workflows".